export const dataHeader = [
  "Firstname",
  "Lastname",
  "Start",
  "Department",
  "Birth",
  "Street",
  "City",
  "State",
  "ZipCode",
];

export const tableItem = [
  {
    firstName: "Jimmy",
    lastName: "Lelievre",
    startDay: "13 fevrier 2010",
    department: "Sales",
    dateOfBirth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipCode: "42100",
  },
  {
    firstName: "Jimmy",
    lastName: "Lelievre",
    startDay: "13 fevrier 2010",
    department: "Sales",
    dateOfBirth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipCode: "42100",
  },
  {
    firstName: "Jimmy",
    lastName: "Lelievre",
    startDay: "13 fevrier 2010",
    department: "Sales",
    dateOfBirth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipCode: "42100",
  },
  {
    firstName: "Jimmy",
    lastName: "Lelievre",
    startDay: "13 fevrier 2010",
    department: "Sales",
    dateOfBirth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipCode: "42100",
  },
  {
    firstName: "bernard",
    lastName: "Lelievre",
    startDay: "13 fevrier 2010",
    department: "Sales",
    dateOfBirth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipCode: "3200",
  },
  {
    firstName: "luc",
    lastName: "Lelievre",
    startDay: "13 fevrier 2010",
    department: "Sales",
    dateOfBirth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipCode: "75000",
  },
  {
    firstName: "Jimmy",
    lastName: "Lelievre",
    startDay: "13 fevrier 2010",
    department: "Sales",
    dateOfBirth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipCode: "42100",
  },
  {
    firstName: "Jimmy",
    lastName: "Lelievre",
    startDay: "13 fevrier 2010",
    department: "Sales",
    dateOfBirth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipCode: "42100",
  },
  {
    firstName: "Gael",
    lastName: "breton",
    startDay: "13 fevrier 2010",
    department: "Sales",
    dateOfBirth: "04/01/2001",
    street: "55 rue du du four",
    city: "paris",
    state: "Alabama",
    zipCode: "42100",
  },
  {
    firstName: "Jimmy",
    lastName: "Lelievre",
    startDay: "13 fevrier 2010",
    department: "Sales",
    dateOfBirth: "04/01/2001",
    street: "244 rue du du four",
    city: "paris",
    state: "Alabama",
    zipCode: "42100",
  },
  {
    firstName: "Jean",
    lastName: "jacque",
    startDay: "13 fevrier 2010",
    department: "Sales",
    dateOfBirth: "04/01/2001",
    street: "20 rue du du four",
    city: "paris",
    state: "Alabama",
    zipCode: "42100",
  },
];
